const jwt = require('jsonwebtoken');

const value = {
    name:"atharv",
    accountNumber:123123
}

const token = jwt.sign(value,"secret");
//this token has been generated by using this secret, and hence this token can only be verified using 
// this token.
console.log(token);
//this created is secret/checkbook in this case, if we loose this we are focked
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYXRoYXJ2IiwiYWNjb3VudE51bWJlciI6MTIzMTIzLCJpYXQiOjE3MDQwODU3NTd9.GV2vAUdvSVPD1M0qKD0-YUL5WAwp0cGQ3oFnoKV9zeE

//verify this signature using the secret, 
//if someone does copy the contend and try to login it wont as they dont know the secret,
//they only see content, they server verifies it using the secret.

const decoded = jwt.verify(token,"secret");
console.log(decoded);
